import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#E4EDF7',
    },
    scrollContainer: {
        paddingVertical: 30,
        alignItems: 'center',
    },
    phoneFrame: {
        width: 375,
        borderRadius: 40,
        backgroundColor: '#EBF2FA',
        padding: 24,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 8, height: 8 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
        elevation: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
    },
    rowHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    profileRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatarPlaceholder: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#D1E3F8',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: '#fff',
    },
    greetingText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1F2937',
    },
    subGreetingText: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 2,
    },
    roundIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F0F4FA',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.4,
        shadowRadius: 4,
        borderWidth: 1,
        borderColor: '#fff',
    },
    sectionTitleText: {
        fontSize: 22,
        fontWeight: '800',
        color: '#1F2937',
        marginVertical: 10,
    },
    pillsRow: {
        flexDirection: 'row',
        marginVertical: 10,
        justifyContent: 'flex-start',
    },
    pillActive: {
        backgroundColor: '#FFFFFF',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 20,
        marginRight: 8,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        borderWidth: 1,
        borderColor: '#fff',
    },
    pillTextActive: {
        fontSize: 12,
        fontWeight: '700',
        color: '#1F2937',
    },
    pillInactive: {
        backgroundColor: 'transparent',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 20,
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    pillTextInactive: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    scoreDataContainer: {
        marginTop: 20,
        marginBottom: 5,
    },
    scoreDeltaBadge: {
        backgroundColor: '#E0F2FE',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 15,
        marginRight: 10,
    },
    scoreDeltaText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#0369A1',
    },
    scoreUpdateBadge: {
        backgroundColor: '#F3F4F6',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 15,
    },
    scoreUpdateText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    scoreAbsolutePlacement: {
        flexDirection: 'row',
        alignItems: 'baseline',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 5,
    },
    hugeScoreDigit: {
        fontSize: 68,
        fontWeight: '300',
        color: '#111827',
        letterSpacing: -1,
    },
    scoreStatusLabelText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#374151',
    },
    gradientTrackBackground: {
        height: 8,
        borderRadius: 4,
        position: 'relative',
        marginTop: 15,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        backgroundColor: '#4ade80',
    },
    sliderIndicatorPointerPin: {
        position: 'absolute',
        top: -8,
        width: 4,
        height: 24,
        backgroundColor: '#FFFFFF',
        borderWidth: 1.5,
        borderColor: '#111827',
        borderRadius: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
    },
    triangleBlackPointerArrowPinIndicator: {
        position: 'absolute',
        bottom: -15,
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 6,
        borderRightWidth: 6,
        borderBottomWidth: 8,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: '#111827',
    },
    gradientAxisLabelsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
        paddingHorizontal: 2,
    },
    axisTicksText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#6B7280',
    },
    accordionCardContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        padding: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 8,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.6)',
        cursor: 'pointer',
    },
    accordionHeaderTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1F2937',
    },
    chevronIconStyle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#4B5563',
    },
    redAlertNotificationBadge: {
        backgroundColor: '#EF4444',
        width: 20,
        height: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    redAlertNotificationText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '800',
    },
    chartWrapperPlaceholderBlock: {
        height: 160,
        backgroundColor: 'rgba(240, 244, 250, 0.5)',
        borderRadius: 16,
        marginTop: 10,
        padding: 12,
        position: 'relative',
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
    },
    chartDateLabelBubbleText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#4B5563',
        alignSelf: 'center',
    },
    chartFloatingMetricIndicatorBox: {
        position: 'absolute',
        top: 50,
        right: 40,
        backgroundColor: '#FFFFFF',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        zIndex: 5,
    },
    chartFloatingMetricIndicatorText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#1F2937',
    },
    mockVerticalGridAxisMarkers: {
        justifyContent: 'space-between',
        height: '85%',
        position: 'absolute',
        left: 12,
        bottom: 12,
    },
    simulatedGraphSplineLine: {
        position: 'absolute',
        bottom: 40,
        left: 50,
        width: 240,
        height: 60,
        borderTopWidth: 3,
        borderLeftWidth: 3,
        borderColor: '#3B82F6',
        borderTopLeftRadius: 120,
        transform: [{ scaleY: -1 }],
        opacity: 0.8,
    },
    simulatedGraphVerticalMarkerDropLine: {
        position: 'absolute',
        bottom: 15,
        right: 105,
        width: 1,
        height: 85,
        backgroundColor: '#34D399',
        borderStyle: 'dashed',
    },
    navigationHeaderBackBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    navigationHeaderMiddleTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#1F2937',
    },
    innerCardBoldSubheading: {
        fontSize: 16,
        fontWeight: '800',
        color: '#1F2937',
    },
    miniRoundArrowButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#111827',
        alignItems: 'center',
        justifyContent: 'center',
    },
    horizontalCalendarTimelineRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginVertical: 15,
    },
    calendarDayColumnItem: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        width: 46,
        height: 70,
        borderRadius: 23,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    calendarDayColumnItemActive: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#3B82F6',
        width: 46,
        height: 70,
        borderRadius: 23,
        shadowColor: '#3B82F6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    calDayLabel: {
        fontSize: 11,
        color: '#6B7280',
        fontWeight: '600',
        marginBottom: 6,
    },
    calDateLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1F2937',
    },
    calDayLabelActive: {
        fontSize: 11,
        color: '#FFFFFF',
        fontWeight: '600',
        marginBottom: 6,
        opacity: 0.9,
    },
    calDateLabelActive: {
        fontSize: 14,
        fontWeight: '800',
        color: '#FFFFFF',
    },
    premiumGlassCreditDetailsCardFrame: {
        backgroundColor: '#FFFFFF',
        borderRadius: 28,
        padding: 20,
        marginTop: 15,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
        cursor: 'pointer',
    },
    bankAvatarIconEmblemBox: {
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    bankAccountCorporateTitleText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1F2937',
    },
    bankAccountLoanProductTagLabelText: {
        fontSize: 11,
        color: '#6B7280',
        fontWeight: '600',
        marginTop: 2,
    },
    metricsGridDimmedCaptionLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#9CA3AF',
    },
    prominentBoldMetricCashValueDisplay: {
        fontSize: 24,
        fontWeight: '800',
        color: '#111827',
        marginTop: 4,
    },
    metricBoldDetailsValueDisplay: {
        fontSize: 13,
        fontWeight: '700',
        color: '#1F2937',
        marginTop: 4,
    },
    dividerHairlineSeparatorLine: {
        height: 1,
        backgroundColor: '#E5E7EB',
        marginVertical: 15,
    },
    largeProductHeaderHeadlineText: {
        fontSize: 24,
        fontWeight: '800',
        color: '#1F2937',
    },
    radialGaugeCircleOuterRingComponent: {
        width: 90,
        height: 90,
        borderRadius: 45,
        borderWidth: 6,
        borderColor: '#F3F4F6',
        borderTopColor: '#F59E0B',
        borderRightColor: '#10B981',
        alignItems: 'center',
        justifyContent: 'center',
        transform: [{ rotate: '45deg' }],
    },
    radialGaugeInnerFaceCircleCenterPlatter: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        transform: [{ rotate: '-45deg' }],
    },
    radialPercentageCoreCenterDigitLabelText: {
        fontSize: 14,
        fontWeight: '800',
        color: '#111827',
    },
    radialSubtextCaptionDescriptionText: {
        fontSize: 8,
        fontWeight: '700',
        color: '#6B7280',
        textTransform: 'uppercase',
        marginTop: 1,
    },
    timelineTargetTopHeaderCaptionAnchorText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#10B981',
        textAlign: 'center',
        marginBottom: 15,
    },
    calendarMatrixFlexLayoutGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    gridMatrixCellItem: {
        width: '16%',
        alignItems: 'center',
        marginVertical: 10,
    },
    matrixMonthTextLabel: {
        fontSize: 11,
        color: '#6B7280',
        fontWeight: '700',
        marginBottom: 6,
    },
    matrixStatusBluePillCircle: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: '#93C5FD',
        alignItems: 'center',
        justifyContent: 'center',
    },
    matrixStatusRedPillCircle: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: '#FCA5A5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    matrixStatusGreyPillCircle: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: '#E5E7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    matrixStatusTextLabel: {
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: '800',
    },
    actionFooterButtonsRowWrapperBox: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 25,
    },
    callToActionButtonSolidLargePrimaryButton: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        paddingVertical: 16,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        borderWidth: 1,
        borderColor: '#fff',
    },
    callToActionButtonTextPayloadLabel: {
        color: '#111827',
        fontSize: 14,
        fontWeight: '800',
    },
    squareIconActionButtonAlternativeContainer: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        borderWidth: 1,
        borderColor: '#fff',
    },
    // Add these properties inside your existing components/styles.ts file:
    authContainer: {
        flex: 1,
        width: 375,
        backgroundColor: '#EBF2FA',
        borderRadius: 40,
        padding: 30,
        justifyContent: 'center',
    },
    authTitle: {
        fontSize: 26,
        fontWeight: '800',
        color: '#1F2937',
        textAlign: 'center',
        marginBottom: 8,
    },
    authSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 30,
    },
    inputLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: '#374151',
        marginBottom: 6,
        marginTop: 14,
    },
    textInputMock: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D1D9E6',
        borderRadius: 16,
        padding: 14,
        fontSize: 14,
        color: '#1F2937',
    },
    authButtonPrimary: {
        backgroundColor: '#1E3A8A',
        borderRadius: 20,
        padding: 16,
        alignItems: 'center',
        marginTop: 26,
        shadowColor: '#1E3A8A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    authButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '800',
    },
    toggleAuthModeButton: {
        marginTop: 16,
        alignItems: 'center',
    },
    toggleAuthModeText: {
        fontSize: 13,
        color: '#3B82F6',
        fontWeight: '600',
    },
    complianceTableCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 28,
        padding: 20,
        marginTop: 15,
        shadowColor: '#A3B1C6',
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.7)',
    },
    tableTableHeaderRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        paddingBottom: 8,
        marginBottom: 10,
    },
    tableDataRow: {
        flexDirection: 'row',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        alignItems: 'center',
    },
    colHeader: {
        fontSize: 12,
        fontWeight: '700',
        color: '#9CA3AF',
    },
    cellTextMain: {
        fontSize: 13,
        fontWeight: '700',
        color: '#1F2937',
    },
    cellTextSub: {
        fontSize: 12,
        fontWeight: '600',
        color: '#4B5563',
    },
    badgePass: {
        backgroundColor: '#D1FAE5',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 8,
    },
    badgePassText: {
        color: '#065F46',
        fontSize: 11,
        fontWeight: '800',
    },
    badgeFail: {
        backgroundColor: '#FEE2E2',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 8,
    },
    badgeFailText: {
        color: '#991B1B',
        fontSize: 11,
        fontWeight: '800',
    },
    badgeStressed: {
        backgroundColor: '#FEF3C7',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 8,
    },
    badgeStressedText: {
        color: '#92400E',
        fontSize: 11,
        fontWeight: '800',
    },
    insightBoxContainer: {
        borderRadius: 20,
        padding: 16,
        marginTop: 12,
        borderWidth: 1,
    },
    insightHeader: {
        fontSize: 13,
        fontWeight: '800',
        marginBottom: 4,
    },
    insightBody: {
        fontSize: 12,
        lineHeight: 16,
        color: '#374151',
        fontWeight: '500',
    },
});

